# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'WTD_Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WTD_Demo
pod 'Alamofire', '~> 4.7'
pod 'AlamofireImage', '~> 3.0'
end
